schema: ./schemas/schema.graphql
extensions:
  endpoints:
    Default GraphQL Endpoint:
      url: http://localhost:7000/graphql
#      url: https://ininderprint-backend-nestjs.cloud-dev.ininderprint.tw/admin-api/graphql
      headers:
        user-agent: JS GraphQL
        Authorization: Bearer bf94d17d-ba37-439f-a35b-73e9f25cbfd7
      introspect: false
